language: node_js
node_js:
    - "0.10"

branches:
    only:
        - master

install:
    - npm install grunt-cli
    - npm install

cache:
    directories:
        - node_modules

script:
    - ./node_modules/.bin/grunt travis
